"""init

Revision ID: a9dbc0693787
Revises: 
Create Date: 2024-05-03 23:06:20.800705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a9dbc0693787'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Author',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор'),
                    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False,
                              comment='Отметка об удалении'),
                    sa.Column('pseudonym', sa.String(), nullable=True, comment='Псевдоним автора'),
                    sa.Column('info', sa.Text(), nullable=False, comment='Информация об авторе'),
                    sa.PrimaryKeyConstraint('id'),
                    comment='Авторы'
                    )
    op.create_table('Album',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор'),
                    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False,
                              comment='Отметка об удалении'),
                    sa.Column('name', sa.String(), nullable=True, comment='Название сборника'),
                    sa.Column('author_id', sa.Integer(), nullable=True, comment='{Author}'),
                    sa.ForeignKeyConstraint(['author_id'], ['Author.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    comment='Сборники'
                    )
    op.create_table('Poem',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор'),
                    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False,
                              comment='Отметка об удалении'),
                    sa.Column('album_id', sa.Integer(), nullable=True, comment='{Album}'),
                    sa.Column('name', sa.String(), nullable=True, comment='Название стихотворения'),
                    sa.Column('content', sa.Text(), nullable=False, comment='Само стихотворение'),
                    sa.ForeignKeyConstraint(['album_id'], ['Album.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    comment='Стихотворения'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Poem')
    op.drop_table('Album')
    op.drop_table('Author')
    # ### end Alembic commands ###
