"""unnecessary information

Revision ID: cfee9648658e
Revises: fe57b0676e7e
Create Date: 2024-05-04 20:41:24.536684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cfee9648658e'
down_revision: Union[str, None] = 'fe57b0676e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Author', 'pseudonym',
                    existing_type=sa.VARCHAR(),
                    nullable=False,
                    existing_comment='Псевдоним автора')
    op.alter_column('Author', 'info',
                    existing_type=sa.TEXT(),
                    nullable=True,
                    existing_comment='Информация об авторе')
    op.create_index(op.f('ix_Author_id'), 'Author', ['id'], unique=False)
    op.add_column('Collection', sa.Column('idx', sa.Integer(), nullable=False, comment='Индекс для сортировки'))
    op.add_column('Collection', sa.Column('description', sa.String(), server_default=sa.text('null'), nullable=True,
                                          comment='Описание'))
    op.add_column('Collection', sa.Column('publish_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                                          nullable=False, comment='Дата публикации'))
    op.alter_column('Collection', 'author_id',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    existing_comment='{Author}')
    op.alter_column('Collection', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False,
                    comment='Название',
                    existing_comment='Название сборника')
    op.create_index(op.f('ix_Collection_id'), 'Collection', ['id'], unique=False)
    op.add_column('Poem', sa.Column('idx', sa.Integer(), nullable=False, comment='Индекс для сортировки'))
    op.add_column('Poem',
                  sa.Column('create_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False,
                            comment='Дата создания'))
    op.alter_column('Poem', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False,
                    comment='Название',
                    existing_comment='Название стихотворения')
    op.alter_column('Poem', 'content',
                    existing_type=sa.TEXT(),
                    comment='Содержимое',
                    existing_comment='Само стихотворение',
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Poem', 'content',
                    existing_type=sa.TEXT(),
                    comment='Само стихотворение',
                    existing_comment='Содержимое',
                    existing_nullable=False)
    op.alter_column('Poem', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True,
                    comment='Название стихотворения',
                    existing_comment='Название')
    op.drop_column('Poem', 'create_date')
    op.drop_column('Poem', 'idx')
    op.drop_index(op.f('ix_Collection_id'), table_name='Collection')
    op.alter_column('Collection', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True,
                    comment='Название сборника',
                    existing_comment='Название')
    op.alter_column('Collection', 'author_id',
                    existing_type=sa.INTEGER(),
                    nullable=True,
                    existing_comment='{Author}')
    op.drop_column('Collection', 'publish_date')
    op.drop_column('Collection', 'description')
    op.drop_column('Collection', 'idx')
    op.drop_index(op.f('ix_Author_id'), table_name='Author')
    op.alter_column('Author', 'info',
                    existing_type=sa.TEXT(),
                    nullable=False,
                    existing_comment='Информация об авторе')
    op.alter_column('Author', 'pseudonym',
                    existing_type=sa.VARCHAR(),
                    nullable=True,
                    existing_comment='Псевдоним автора')
    # ### end Alembic commands ###
