"""Rename album in collection

Revision ID: fe57b0676e7e
Revises: a9dbc0693787
Create Date: 2024-05-04 17:23:37.051573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'fe57b0676e7e'
down_revision: Union[str, None] = 'a9dbc0693787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Collection',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор'),
                    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False,
                              comment='Отметка об удалении'),
                    sa.Column('name', sa.String(), nullable=True, comment='Название сборника'),
                    sa.Column('author_id', sa.Integer(), nullable=True, comment='{Author}'),
                    sa.ForeignKeyConstraint(['author_id'], ['Author.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    comment='Сборники'
                    )

    op.add_column('Poem', sa.Column('collection_id', sa.Integer(), nullable=True, comment='{Collection}'))
    op.drop_constraint('Poem_album_id_fkey', 'Poem', type_='foreignkey')
    op.create_foreign_key(None, 'Poem', 'Collection', ['collection_id'], ['id'])
    op.drop_column('Poem', 'album_id')
    op.drop_table('Album')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Poem', sa.Column('album_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='{Album}'))
    op.drop_constraint(None, 'Poem', type_='foreignkey')
    op.create_foreign_key('Poem_album_id_fkey', 'Poem', 'Album', ['album_id'], ['id'])
    op.drop_column('Poem', 'collection_id')
    op.create_table('Album',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Album_id_seq"\'::regclass)'),
                              autoincrement=True, nullable=False, comment='Идентификатор'),
                    sa.Column('deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False,
                              nullable=False, comment='Отметка об удалении'),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Название сборника'),
                    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='{Author}'),
                    sa.ForeignKeyConstraint(['author_id'], ['Author.id'], name='Album_author_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='Album_pkey'),
                    comment='Сборники'
                    )
    op.drop_table('Collection')
    # ### end Alembic commands ###
